server:
  port: 8012
spring:
  application:
    name: feign-provider
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01.sagesource.com:8761/eureka/,http://eureka-server-02.sagesource.com:8762/eureka/,http://eureka-server-03.sagesource.com:8763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'