server:
  port: 8014
spring:
  application:
    name: hystrix-provider-service

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01.sagesource.com:8761/eureka/,http://eureka-server-02.sagesource.com:8762/eureka/,http://eureka-server-03.sagesource.com:8763/eureka/
    # 适当提高拉取server信息的频率
    registry-fetch-interval-seconds: 5

# 添加监控点，便于hystrix dashboard 获取状态
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream