server:
  port: 8011
spring:
  application:
    name: feign-client

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01.sagesource.com:8761/eureka/,http://eureka-server-02.sagesource.com:8762/eureka/,http://eureka-server-03.sagesource.com:8763/eureka/

# 日志配置
logging:
  level:
    io.sagesource.springcloud.tutorial.feign.client.service.GithubFeignService: debug

## feign 配置
# 启动okhttp
feign:
  httpclient:
    enabled: false
  okhttp:
    enable: true