spring:
  profiles:
    active: standalone
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: EUREKA-SERVER

management:
  endpoints:
    web:
      exposure:
        include: '*'