# eureka server peer3 config
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-server-03.sagesource.com
  client:
    # 表示是否注册自身到eureka服务器
    #register-with-eureka: true
    # 是否从eureka上获取注册信息
    #fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-01.sagesource.com:8761/eureka/,http://eureka-server-02.sagesource.com:8762/eureka/
  server:
    # 在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒
    wait-time-in-ms-when-sync-empty: 0
    # 针对client下线但是没有通知到eureka server的问题，调整定时任务频率为5s
    eviction-interval-timer-in-ms: 5000
    # 关闭 eureka server 一级缓存
    use-read-only-response-cache: false
    # 修改 eureka server 二级guava缓存的失效时间
    response-cache-auto-expiration-in-seconds: 10